### PR TITLE
RayTracer Scala Semester Project from Timo

### PR DESCRIPTION
**Pull request by Geheiner**

### CODE REVIEW

**Comment by DarkDimius** [comment]
https://github.com/DarkDimius/scala-blitz/commit/c52290e82a138dc0512a3bca8ce4c901f454040f

**Comment by DarkDimius** [comment]
Before merging, I'd like to add a scalameter regression test.
I'll have time next week, but you can volunteer to do it

**Comment by Geheiner** [comment]
As for scalameter, I do not have much time during the next few weeks unfortunately because of exam revision.

**Comment by DarkDimius** [comment]
Your changes are incorporated in this PR
https://github.com/scala-blitz/scala-blitz/pull/35

**Pull request closed without merging**
